ALTER TABLE students ALTER COLUMN university DROP NOT NULL;
ALTER TABLE students ALTER COLUMN region DROP NOT NULL;
ALTER TABLE students ALTER COLUMN specialty DROP NOT NULL;
ALTER TABLE students ALTER COLUMN cluster DROP NOT NULL;
ALTER TABLE students ALTER COLUMN year_of_study DROP NOT NULL;
ALTER TABLE students ALTER COLUMN gpa_scale DROP NOT NULL;
ALTER TABLE students ALTER COLUMN gpa_value DROP NOT NULL;
